### ISSUE TITLE
ACE medical rewrite breaks the newly added ACE compatibility in the dev versions

### ISSUE THREAD

**Issue by Houlton72** [NeoArmageddon/co10_Escape#45]
Upon taking what ACE deems as "Fatal damage" you now enter cardiac arrest which doesn't seem to be recognised in escape, causing you to once succumb to cardiac arrest, die and respawn with the full loadout of whatever unit you are playing as

**Comment by Belkon** [comment]
The rewrite got rid of the unconscious ACE feature and replaced it with the new cardiac arrest one. That said it is not possible to keep a player from dying. Since escape is programmed around keeping players alive, there is no way to create a workout that will work with the current escape code and the new ace medical system. A more complex code could work but that would take some time to develop and I currently don't have the time.

Until the devs re-implement the indefinite unconscious system, all users will need to use an older version of ACE.
