### ISSUE TITLE
Please make a repository for A3VR

### ISSUE THREAD

**Issue by Bluscream** [NeoArmageddon/co10_Escape#56]
Tausende leute warten darauf :pensive:

**Comment by NeoArmageddon** [comment]
Closed for being unrelated to Escape.

**Comment by Bluscream** [comment]
Willst du den Rest deines Lebens tuen als wäre A3VR nie passiert? Solange du das kapitel nicht abschließt wird es keine ruhe geben !

**Comment by NeoArmageddon** [comment]
Was maßt du dir hier eigentlich für eine Dreistigkeit an?
1. Ich entscheide, woran ich in meiner Freizeit arbeite und woran nicht.
2. Das hier hat mit dem Thema nichts zu tun und was du tust ist nicht nur gegen die Nutzerrichtlinien von Github, es grenzt auch schon Belästigung! Was kommt als nächstes? Briefe oder Personen an meiner Haustür mit "Wann kommt VR"?
3. A3VR war ein Experiment wo sich gezeigt hat, dass es sich Arma nicht für VR eignet. Auch wenn ich es "releasen" würde, könnte NIEMAND damit etwas anfangen, der es nicht selbst auch schneller und besser entwickeln könnte. Ich hab das Zeug in den Videos in wortwörtlich einem Tag zusammengekloppt. Das EINZIGE was funktioniert, ist ein grobes Tracking der Geräte! NICHTS WEITERES! Damit kann man weder ein AddOn noch eine Mission erstellen, noch Arma in VR spielen. Und wie gesagt, jeder mit nur etwas Programmiererfahrung kann soetwas in einem Tag selber machen.
4. DAS KAPITEL IST ABGESCHLOSSEN! Es wird kein A3VR von mir geben. Ich werde keinen Code rausgeben, da soetwas nur dazu führt, dass ich noch mehr Nachrichten und "Du musst...."! Nachrichten bekomme. Und dafür habe ich neben meinem Beruf und meinen anderen Projekten die ich schon genug vernachlässigen muss KEINE ZEIT.

Wenn dir das Thema so wichtig ist, dann bau doch selbst VR für Arma3.

**Comment by NeoArmageddon** [comment]
And for everybody stumbling upon this ticket in the future:
As I get a lot of messages about this (A3VR videos on YT) and why there is no development, I want to clear this up a bit:
This was a quick test I put together in nearly one day, there is little to no sophistication and it is clearly not useable to get VR into Arma3. I am sure anybody with more experience can put someting similar together faster and better. I get a lot of messages that "demand" I release this and it has come to a point where I am not only annoyed by really rude and entitled messages but also feel a big impact on my creativity and productivity. I now that I don't owe anyone anything but as there also much friendlier people out there I will list why I choose to not further develop this and why there won't be any release:
1.) It is really just a hacky solution and a lot of stuff is staged ingame for the videos. The scripts need to be changed in many placed for different use scenarios which is not useful for anyone in Arma3. You can't just drop this in and make a mission with it.
2.) There is no stereo rendering. This needs to be done by external tools and I found that most of them are lackingin performance. VR has come a long way since then and 30 FPS motion and view with FPS drops is just not useable for gaming.
3.) I won't release any code/script/addon for three reasons: First off, it is just a hacky script and dll that won't help anybody adding VR to Arma. Everybody who could make use of this can do this better and faster himself anyway. Second, for me releasing something is always attached with some kind of responsibility and for this I don't have the time, nor the energy. Looking at how many messages I get for really old project where peopel demand(!) support for something I made in my spare time and released for free makes me really anxious about releasing something I don't feel comfortable putting in other peoples hand. And third, I used some libraries and code where the license does not allow a release in binary or source form.

So please, refrain from asking me about this, demand to release it or spam me with messages on every platform you find me.
Of course everybody is free to write me a nice message to have a chat about Arma and VR in general.
