### ISSUE TITLE
CAS does not work on dedicated server

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#65]
A few months ago the CAS script was updated, and while it does work on a local host, I've noticed in the past few months I've never seen CAS when playing on a dedicated server.  I retested the script by making CAS attack frequently on a local host and it worked fine, however when I tested the same changes on a dedicated server it still doesn't work.  

I tried changing the `createVehicleLocal` line in fn_CallCAS to just `createVehicle` but that doesn't seem to work.

To test this I've attached the sqf files with the fast respawning CAS
[edited scripts.zip](https://github.com/NeoArmageddon/co10_Escape/files/4594687/edited.scripts.zip)

**Comment by NeoArmageddon** [comment]
Changes to CAS scripts are unrelated to it not working anymore. Seems like BI changed behaviour of scripted logics/modules and the BIS_FNC_CAS script.

**Comment by NeoArmageddon** [comment]
Ok, seems like different problems came together here:

1. BI changed how SideLogic worked and how modules are spawned (sometime early 2018, which broke the direct spawen of the CAS module). This was fixed by creating a logic and run the module script directly. This broke in a later A3 update again as creating the logic by createVehicle was now forbidden by the engine.
2. The BI CAS module checks for specific weapon inheritance and (some) CUP planes have a noon standard inheritance of weapons and thus are excluded from CAS (despite having CAS weapons). This is a CUP bug.

Now attemps by me and @Qerbas trying to fix 1. was masked by 2. so trial and error didn't worked correctly when not testing vanilla.
With the latest commit CAS seems to spawn reliable. Removing planes unable to CAS from unitclassis is ToDo. Ticket for CUP is out: https://dev.cup-arma3.org/T3964
